# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-17 19:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import hacker.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', hacker.fields.DegreeField(help_text='Which academic degree are you hoping to achieve?')),
                ('year', hacker.fields.YearField(help_text='estimate the year during which you are expected to graduate')),
                ('university', hacker.fields.UniField(help_text='use other if not listed')),
            ],
        ),
        migrations.CreateModel(
            name='Approval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approval', models.BooleanField(default=False, help_text='Has the application been approved?')),
            ],
        ),
        migrations.CreateModel(
            name='HackathonApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whyJacobsHack', models.TextField()),
                ('firstHackathon', models.BooleanField(default=False, help_text='JacobsHack is my first Hackathon')),
                ('whatHaveYouBuilt', models.TextField(help_text='E.g. GitHub Link, Devpost, Personal Projects ...')),
            ],
        ),
        migrations.CreateModel(
            name='Hacker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(help_text='Your first name', max_length=255)),
                ('middleName', models.CharField(blank=True, help_text='Your middle name(s)', max_length=255, null=True)),
                ('lastName', models.CharField(help_text='Your last name', max_length=255)),
                ('email', models.EmailField(help_text='Your email address', max_length=254, unique=True)),
                ('nationality', hacker.fields.CountryField(help_text='You can select multiple options by holding the <em>Ctrl</em> key (or <em>Command</em> on Mac) while clicking', max_length=746, multiple=True)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Organizational',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shirtSize', hacker.fields.ShirtSizeField(help_text='Select your EU T-Shirt size. ')),
                ('needVisa', models.BooleanField(default=False, help_text='I need a Visa to come to Germany and attend JacobsHack')),
                ('dietaryRequirements', models.TextField(blank=True, help_text='e.g. Vegan, Vegetarian, Gluten-free ...')),
                ('comments', models.TextField(blank=True, help_text='If you are applying as a Team, mention the names of your teammates here. ')),
                ('hacker', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='organizational', to='hacker.Hacker')),
            ],
        ),
        migrations.AddField(
            model_name='hackathonapplication',
            name='hacker',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='application', to='hacker.Hacker'),
        ),
        migrations.AddField(
            model_name='approval',
            name='hacker',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='approval', to='hacker.Hacker'),
        ),
        migrations.AddField(
            model_name='academicdata',
            name='hacker',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='academic', to='hacker.Hacker'),
        ),
    ]
