# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-19 21:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hacker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizational',
            name='reimburse',
            field=models.BooleanField(default=False, help_text='Are you travelling from outside of Germany?'),
        ),
    ]
