# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-04 19:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import hacker.models


class Migration(migrations.Migration):

    dependencies = [
        ('hacker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CV',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cv', models.FileField(blank=True, help_text='Your CV (optional)', null=True, upload_to=hacker.models.upload_to)),
                ('hacker', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cv', to='hacker.Hacker')),
            ],
        ),
    ]
