# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-19 22:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hacker', '0002_organizational_reimburse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizational',
            name='reimburse',
        ),
    ]
