# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-19 22:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hacker', '0003_remove_organizational_reimburse'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizational',
            name='reimburse',
            field=models.BooleanField(default=False, help_text='Are you coming from outside of Bremen?'),
        ),
    ]
