# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-19 22:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hacker', '0004_organizational_reimburse'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organizational',
            old_name='reimburse',
            new_name='needReimbursement',
        ),
    ]
