# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-29 18:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hacker', '0008_auto_20180729_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hacker',
            name='jacobsHackTerms',
            field=models.BooleanField(help_text="I have read and agree to the <a href='/terms/' target='_blank'>JacobsHack Terms and Conditions</a>, including the <a href='/privacy/' target='_blank'>Privacy Policy</a>. "),
        ),
    ]
