# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-03 04:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hacker', '0009_auto_20180729_1813'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hacker',
            name='mlhEmailConsent',
        ),
        migrations.AddField(
            model_name='hacker',
            name='mlhSharingConsent',
            field=models.BooleanField(default=False, help_text="I authorize you to share my application/registration information for event administration, ranking, MLH administration, pre- and post-event informational e-mails, and occasional messages about hackathons in-line with the <a href='https://mlh.io/privacy' target='_blank'>MLH Privacy Policy</a>. "),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hacker',
            name='mlhCodeOfConduct',
            field=models.BooleanField(help_text="I have read and agree to the <a href='https://mlh.io/code-of-conduct'>MLH Code of Conduct</a>. "),
        ),
        migrations.AlterField(
            model_name='hacker',
            name='mlhContestTerms',
            field=models.BooleanField(help_text="I agree to the terms of both the <a href='https://github.com/MLH/mlh-policies/tree/master/prize-terms-and-conditions'>MLH Contest Terms</a> and the <a href='https://mlh.io/privacy' target='_blank'>MLH Privacy Policy</a>. "),
        ),
    ]
