# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-03 04:36
from __future__ import unicode_literals

from django.db import migrations
import hacker.fields


class Migration(migrations.Migration):

    dependencies = [
        ('hacker', '0010_auto_20180803_0415'),
    ]

    operations = [
        migrations.AddField(
            model_name='hacker',
            name='countryOfResidence',
            field=hacker.fields.CountryField(default='DE', max_length=2),
            preserve_default=False,
        ),
    ]
