# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-03 05:52
from __future__ import unicode_literals

from django.db import migrations
import hacker.fields


class Migration(migrations.Migration):

    dependencies = [
        ('hacker', '0012_hacker_phonenumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='hacker',
            name='gender',
            field=hacker.fields.FuzzyChoiceField(data=['Male', 'Female', 'Prefer Not To Answer'], default='Prefer Not To Answer', help_text="Pick one of 'Male' , 'Female' , 'Prefer Not To Answer' or specify a custom one. ", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hacker',
            name='race',
            field=hacker.fields.FuzzyChoiceField(data=['American Indian or Alaskan Native', 'Asian / Pacific Islander', 'Black or African American', 'Hispanic', 'White / Caucasian', 'Prefer Not To Answer'], default='Prefer Not To Answer', help_text="Pick one of 'American Indian or Alaskan Native' , 'Asian / Pacific Islander' , 'Black or African American' , 'Hispanic' , 'White / Caucasian' , 'Prefer Not To Answer' or specify a custom one. ", max_length=255),
            preserve_default=False,
        ),
    ]
