# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-03 06:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hacker', '0015_auto_20180803_0613'),
    ]

    operations = [
        migrations.AddField(
            model_name='hacker',
            name='dob',
            field=models.DateField(default=django.utils.timezone.now, help_text='Date of Birth'),
            preserve_default=False,
        ),
    ]
