# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-03 06:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hacker', '0016_hacker_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hacker',
            name='dob',
            field=models.DateField(),
        ),
    ]
