# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-03 06:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hacker', '0017_auto_20180803_0633'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicdata',
            name='major',
            field=models.CharField(default='None', help_text='What is your current major?', max_length=255),
            preserve_default=False,
        ),
    ]
