# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-03 06:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hacker', '0018_academicdata_major'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hacker',
            name='mlhSharingConsent',
        ),
        migrations.AlterField(
            model_name='hacker',
            name='mlhContestTerms',
            field=models.BooleanField(help_text="I authorize you to share my application/registration information for event administration, ranking, MLH administration, pre- and post-event informational e-mails, and occasional messages about hackathons in-line with the <a href='https://mlh.io/privacy' target='_blank'>MLH Privacy Policy</a>. I agree to the terms of both the <a href='https://github.com/MLH/mlh-policies/tree/master/prize-terms-and-conditions'>MLH Contest Terms</a> and the <a href='https://mlh.io/privacy' target='_blank'>MLH Privacy Policy</a>. "),
        ),
    ]
