# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-05 21:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hacker', '0020_auto_20180805_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hackathonapplication',
            name='firstHackathon',
            field=models.BooleanField(default=False, help_text='JacobsHack! is my first Hackathon. '),
        ),
        migrations.AlterField(
            model_name='hacker',
            name='jacobsHackTerms',
            field=models.BooleanField(help_text="I have read and agree to the <a href='/terms/' target='_blank'>JacobsHack! Terms and Conditions</a>, including the <a href='/privacy/' target='_blank'>Privacy Policy</a>. "),
        ),
        migrations.AlterField(
            model_name='organizational',
            name='needVisa',
            field=models.BooleanField(default=False, help_text='I need a Visa to come to Germany and attend JacobsHack!. '),
        ),
    ]
