# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-09-09 15:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hacker', '0022_auto_20180806_0022'),
    ]

    operations = [
        migrations.CreateModel(
            name='RSVP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('going', models.BooleanField(default=False, help_text='Are you coming to jacobsHack! 2018?')),
                ('hacker', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rsvp', to='hacker.Hacker')),
            ],
        ),
    ]
