# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-23 20:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hacker', '0023_rsvp'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizational',
            name='passportNumber',
            field=models.CharField(blank=True, default='', help_text='Your passport number (if you need a visa)', max_length=255, null=True),
        ),
    ]
